/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QPDAO;

import Utils.BaseDAO;
import static Utils.BaseDAO.closeCon;
import static Utils.BaseDAO.getCon;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Abha Suntwal
 */
public class tableDAO {

    public static void importTable(String fileAddr) {

        Connection con = null;
        try {
            con = getCon();
            //The id is quto generated, hence not inserting its values from the below query
            String query = " insert into question_bank (question,discrimination,time,difficulty,marks,relevancy,frequency,year) values (?,?,?,?,?,?,?,?)";
            PreparedStatement st = con.prepareStatement(query);

            //using file
            FileInputStream fileIn = new FileInputStream(new File(fileAddr));

            //Complusary download Apache POIJar link and then use XSSFWorkbook..
            XSSFWorkbook wb = new XSSFWorkbook(fileIn);
            XSSFSheet sheet = wb.getSheetAt(0);
            Row row;

            //The below println is to check the number of rows our code is recognizing from the excel file, to prevent nullpointerexception
            System.out.println("last row = " + sheet.getLastRowNum());
            
            for (int i = 1; i <= sheet.getLastRowNum(); i++) {
                row = sheet.getRow(i);
                
                // st.setInt(1, (int)row.getCell(0).getNumericCellValue());   being an autogenerated value
                st.setString(1, row.getCell(1).getStringCellValue());
                st.setInt(2, (int) row.getCell(2).getNumericCellValue());
                st.setInt(3, (int) row.getCell(3).getNumericCellValue());
                st.setInt(4, (int) row.getCell(4).getNumericCellValue());
                st.setInt(5, (int) row.getCell(5).getNumericCellValue());
                st.setInt(6, (int) row.getCell(6).getNumericCellValue());
                st.setInt(7, (int) row.getCell(7).getNumericCellValue());
                st.setInt(8, (int) row.getCell(8).getNumericCellValue());
                st.execute();
            }
            JOptionPane.showMessageDialog(null, "Successfully imported into the database!");
            
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            closeCon(con);
        }

    }

}
